### ISSUE TITLE
Server(Firebase + Flask) Part

### ISSUE THREAD

**Issue by Sikurity** [ProjectInTheClass/HyLionPost#19]
1. Crawling Part에서 작성된 함수를 Timer를 통해 주기적으로 호출
 - Flask 서버에서 주기적으로 게시판들을 크롤링
 - 새로운 게시글이 확인 된 경우, Firebase 주제 메시징 기능을 이용해 Push

2. 첫 App 사용 시, 기본적인 게시글들에 대한 요청 처리
 - 기본 게시글들에 대한 요청이 있으면, 최신글 10개 정도를 DB에서 꺼내어 반환

3. Firebase에 iOS Development Certification 등록 및 환경설정
 - iPhone Device에 Push Notification을 해주기 위해서는 인증서 등록을 해주어야 함

**Comment by PineApple777** [comment]
[https://github.com/olucurious/PyFCM](https://github.com/olucurious/PyFCM)

**Comment by PineApple777** [comment]
[https://pypi.python.org/pypi/APScheduler](https://pypi.python.org/pypi/APScheduler)
