### ISSUE TITLE
Web Crawling Part

### ISSUE THREAD

**Issue by Sikurity** [ProjectInTheClass/HyLionPost#20]
1. 서비스 제공 대상 게시판 크롤링(스크래핑) 기능 구현
 - 특성화사업단(csck2notice)
 - 컴퓨터소프트웨어학부 졸업프로젝트 게시판(csgradu)
 - 컴퓨터소프트웨어학부 취업정보 게시판(csjob)
 - 컴퓨터소프트웨어학부 학사일반 게시판(csnotice)
 - 컴퓨터소프트웨어학부 삼성트랙 게시판(csstrk)
 - 컴퓨터소프트웨어학부 학생 게시판(csstu)

2. 게시판 별 Key, Title, URL, Date 추출

3. Flask 서버에서 호출하여 사용할 수 있도록 함수화

**Comment by PineApple777** [comment]
크롤러에서 데이터가 생성된 이후에 만들어지는 json 파일이 크롤러가 저장된 곳이 아닌, 서버가 실행되는 곳에 만들어 지네요. 
혹시 파일이 생성되는 지점을 따로 설정해두셨나요 아니면 그냥 default로 / 에 생성되는 건가요.
제가 보기에는 디폴트로 server가 실행되는 곳이 root라 자동으로 server 폴더에 생성되는거 같네요. 
혹시 따로 경로 설정이 가능한가요.

**Comment by CameliaOvO** [comment]
생성지점을 안 정하고 server.py가 크롤러 함수를 그대로 가져와서 그런 거 맞아요.

그럼 크롤러 결과들을 (HyLionPost/server/result)라고 폴더를 만들어서 넣도록 수정할까요?? 아니면 (HyLionPost/crawlers/crawler/result)에 넣을까요??

**Comment by PineApple777** [comment]
크롤러 파트에 정리하면 좋을꺼 같네욤 : )
데이터를 크롤러에서 긁어 왔으니 크롤러에 정리하는게 맞다고 생각합니다~ : )
