### ISSUE TITLE
App UI design

### ISSUE THREAD

**Issue by CameliaOvO** [ProjectInTheClass/HyLionPost#22]
https://developer.apple.com/design/tips/kr/
 - HIG에서 몇몇 중요 부분만 한국어로 번역된 부분 !

https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/
 - HIG (app icon)

**Comment by CameliaOvO** [comment]
* 원래 한 페이지에서 하단 버튼을 통해 (하단버튼) - (관심글 모아보기, 필터, 기간검색)을 하려 했던 것을
 탭바를 만들어서 [새글] - [관심글]  - [관심게시판, 전체게시판] 으로 만들면 어떨까요??

**Comment by CameliaOvO** [comment]
![star-512colored](https://cloud.githubusercontent.com/assets/15843266/26819232/f002b2bc-4ad8-11e7-8af8-fe47fea192b1.png)
![star-512](https://cloud.githubusercontent.com/assets/15843266/26819236/f2319d00-4ad8-11e7-83e9-d158f8164b04.png)

**Comment by PineApple777** [comment]
피드백 목록
1. 색상 변경 필요
2. 과도하게 큰 “현재 최신 버전 입니다” 글자 부분 -> 중요한 부분인가?
3. 환경설정 부분의 2개의 탭에 >를 넣었으면 한다
4. 탭이 꼭 흰색 이어야 하나?
5. 환경설정 -> 앱정보 로 앱정보를 새로운 뷰로 보여줘도 되지 않을까?
6. 앱 사진 부분 모서리 둥글게 변경
7. 우체통은 완성도 높다고 함

**Comment by PineApple777** [comment]
[http://ivomynttinen.com/blog/ios-design-guidelines](http://ivomynttinen.com/blog/ios-design-guidelines)
[https://color.adobe.com/ko/create/color-wheel/](https://color.adobe.com/ko/create/color-wheel/)
[https://codepen.io/](https://codepen.io/)
