### ISSUE TITLE
여기에 풀 리퀘 보내도 되요?

### ISSUE THREAD

**Issue by benjioh5** [ProjectInTheClass/HyLionPost#4]
@PineApple777 가능한가요?

**Comment by Sikurity** [comment]
저희 프로젝트가 전공 강의로 진행되는 거라
다른 팀들과의 공정성을 위해 지금은 힘들 것 같습니다...

그렇지만 이번 학기가 끝나고 나면 언제든지 환영입니다!

**Comment by benjioh5** [comment]
네 알겠습니다!
