### ISSUE TITLE
iOS와 firebase 연동하기

### ISSUE THREAD

**Issue by PineApple777** [ProjectInTheClass/HyLionPost#5]
iOS와 firebase 연동하기.
각종 설정 방법 파악 필요
연관된 링크 comment로 남겨주세요 @CameliaOvO @Sikurity 
server directory에서 README.md 파일로 매뉴얼 계속 업로드 하겠습니다.
필요한거 있으면 여기 요청해주세용
[server로 이동하기](https://github.com/ProjectInTheClass/HyLionPost/tree/master/server)

**Comment by Sikurity** [comment]
Kakao로 계정 인증할려 그랬는데, 아직 Firebase - Kakao 인증은 공식적으로 지원이 안되고 있네요 ㅠ

# [Firebase - Kakao Login for Android](https://github.com/firebase/custom-auth-samples)

제가 목요일까지 위에 코드를 한 번 iOS에도 적용되나 수정해서 테스트해보고
안되면 시간상 Email/Password, Gmail, Facebook으로 해야겠네요

+ [참고 1](https://devtalk.kakao.com/t/firebase/30575/2)
+ [참고 2](https://devtalk.kakao.com/t/kakaotalk-firebase-cloud-messaging/29064)

**Comment by PineApple777** [comment]
그러네요 ㅠ firebase 쪽 공식 문서에는 kakao가 없네요 ㅠ
공식 문서 위주로 저도 공부 계속 하겠습니다 ㅠ
