### ISSUE TITLE
github page 만들기

### ISSUE THREAD

**Issue by PineApple777** [ProjectInTheClass/HyLionPost#6]
- jekyll로 초기 페이지 만들기
- 이를 깃허브로 호스팅 해서 열기
- 기타
계속해서 update 하겠습니다.
필요하거나 도움되는거 올려주세요. @CameliaOvO @Sikurity

**Comment by Sikurity** [comment]
Kakao로 계정 인증할려 그랬는데, 아직 Firebase - Kakao 인증은 공식적으로 지원이 안되고 있네요 ㅠ

# [Firebase - Kakao Login for Android](https://github.com/firebase/custom-auth-samples)
제가 목요일까지 위에 코드를 한 번 iOS에도 적용되나 수정해서 테스트해보고

안되면 시간상 Email/Password, Gmail, Facebook으로 해야겠네요

+ [참고 1](https://devtalk.kakao.com/t/firebase/30575/2)
+ [참고 2](https://devtalk.kakao.com/t/kakaotalk-firebase-cloud-messaging/29064)

**Comment by PineApple777** [comment]
현재 fork 떠서 페이지 테스트 중입니다.

**Comment by PineApple777** [comment]
기초 페이지 완성
파일 정리가 안될꺼 같아서 일반적으로 사용하는 부트스트랩으로 재구성 했습니다~
[페이지 이동하기](https://projectintheclass.github.io/HyLionPost/intro.html)
