### ISSUE TITLE
Python으로 Firebase에 Push 요청하는 방법

### ISSUE THREAD

**Issue by Sikurity** [ProjectInTheClass/HyLionPost#8]
# Firebase Cloud Messaging 과 함께 푸쉬 지원

Python으로 FCM (Firebase Cloud Messaging) 을 이용하여 앱에 푸쉬를 지원해봅시다.

## 참고한 문서
* [iOS에서 Firebase 클라우드 메시징 클라이언트 앱 설정](https://firebase.google.com/docs/cloud-messaging/ios/client?hl=ko)
* [FCM 메시지 정보](https://firebase.google.com/docs/cloud-messaging/concept-options?hl=ko)
* ~[Android에서 Firebase 클라우드 메시징 클라이언트 앱 설정](https://firebase.google.com/docs/cloud-messaging/android/client?hl=ko)~

## 파이썬을 통한 푸쉬 요청 예제
~자세한 내용은 어차피 필요 없을 거 같아 무작정 예시 들어갑니다...~
다음은 requests 라이브러리를 활용한 푸쉬요청 예제입니다. 
(예제의 server_key 는 Firebase Console 의 Project Settings > CLOUD MESSAGING 탭에서 확인 가능)

```
# -*- coding: utf-8 -*-
import json
import requests


def main(server_key, token, message_body):
    headers = {
        'Authorization': 'key= ' + server_key,
        'Content-Type': 'application/json',
    }

    data = {
        'to': token,
        'data': {
            'message_body': message_body,
        },
    }

    response = requests.post('https://fcm.googleapis.com/fcm/send', headers=headers, data=json.dumps(data))
    print(response)


if __name__ == '__main__':
    server_key = '----'  # Firebase Project Settings > CLOUD MESSAGING
    token = '----'       # User's refreshed Token
    message_body = ''    # 푸쉬 메세지
    main(server_key, token, message_body)
```

**Comment by PineApple777** [comment]
[https://firebase.google.com/docs/cloud-messaging/ios/client?hl=ko](https://firebase.google.com/docs/cloud-messaging/ios/client?hl=ko)

**Comment by Sikurity** [comment]
ㅋㅋㅋㅋ 무의식적으로 안드로이드를

**Comment by PineApple777** [comment]
감사합니다 ㅠㅠ 저거 참고해서 서버쪽 완성을 향해 가겠습니다 ㅠ
